import { UserProvider } from '@auth0/nextjs-auth0/client'
import './globals.css'
import type { Metadata } from 'next'
import DataProvider from '@/contexts/DataContext'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css';
// import { ToastContainer } from 'react-toastify'


export const metadata: Metadata = {
  title: 'Elite Ride Admin Dashboard',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <UserProvider>
      <html lang="en">
        <body>
          {children}
          <ToastContainer
            position="top-right"
            autoClose={5000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="light"
          />
        </body>
      </html>
    </UserProvider>
  )
}
