import { UserProvider } from '@auth0/nextjs-auth0/client'
import './globals.css'
import type { Metadata } from 'next'
import DataProvider from '@/contexts/DataContext'


export const metadata: Metadata = {
  title: 'Elite Ride Admin Dashboard',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <UserProvider>

      <html lang="en">
        <body>{children}</body>
      </html>
    </UserProvider>
  )
}
